// Generated by CoffeeScript 1.7.1
(function() {
  var Enum, StopIteration, lp, prototype, puts;

  StopIteration = {
    name: "stop iteration"
  };

  puts = console.log;

  lp = function(f) {
    var _results;
    try {
      _results = [];
      while (true) {
        _results.push(f());
      }
      return _results;
    } catch (_error) {
      StopIteration = _error;
    }
  };

  prototype = {
    check: function() {
      if (this.i >= this.array.length) {
        throw StopIteration;
      }
    },
    peek: function() {
      this.check();
      return this.array[this.i];
    },
    next: function() {
      var result;
      result = this.peek();
      this.i++;
      return result;
    }
  };

  Enum = function(array, i) {
    var eunm;
    if (i == null) {
      i = 0;
    }
    eunm = Object.create(prototype);
    eunm.array = array;
    eunm.i = i;
    return eunm;
  };

  module.exports = {
    loop: lp,
    Enum: Enum
  };

}).call(this);

//# sourceMappingURL=enum.map
