// Generated by CoffeeScript 1.7.1
(function() {
  var arr, count_behave_right, inv, mod;

  mod = require('../count_inversions');

  arr = [1, 2, 3, 4, 3, 2, 1];

  inv = 9;

  count_behave_right = function(count) {
    return it("should count number of inversions", function() {
      return expect(count(arr)).toEqual(inv);
    });
  };

  describe('naive_count', function() {
    var count;
    count = mod.naive_count;
    return count_behave_right(count);
  });

  describe('count_by_merge', function() {
    var count;
    count = mod.count_by_merge;
    return count_behave_right(count);
  });

}).call(this);

//# sourceMappingURL=counting_inversions_spec.map
