// Generated by CoffeeScript 1.7.1
(function() {
  var app, by_enum, correctly_draw, correctly_draw_example;

  app = require("../drawing_skyline");

  by_enum = require("../merge_by_enum");

  correctly_draw_example = function(draw, buildings, lines) {
    return it("should compute the skyline of buildings", function() {
      return expect(draw(buildings)).toEqual(lines);
    });
  };

  correctly_draw = function(draw) {
    describe("for contiguous examples", function() {
      var buildings, lines;
      buildings = [[0, 3, 1], [1, 6, 3], [4, 8, 4], [5, 9, 2], [7, 14, 3], [10, 12, 6], [11, 17, 1], [13, 16, 2]];
      lines = [[0, 1, 1], [1, 4, 3], [4, 8, 4], [8, 10, 3], [10, 12, 6], [12, 14, 3], [14, 16, 2], [16, 17, 1]];
      return correctly_draw_example(draw, buildings, lines);
    });
    return describe("for non-contiguous examples", function() {
      var buildings, lines;
      buildings = [[0, 3, 1], [1, 6, 3], [4, 8, 4], [5, 9, 2], [10, 12, 6], [11, 17, 1], [13, 16, 2]];
      lines = [[0, 1, 1], [1, 4, 3], [4, 8, 4], [8, 9, 2], [10, 12, 6], [12, 13, 1], [13, 16, 2], [16, 17, 1]];
      return correctly_draw_example(draw, buildings, lines);
    });
  };

  describe('skylines', function() {
    describe('draw_by_merge', function() {
      return correctly_draw(app.draw_by_merge);
    });
    return describe('draw_by_merge, with merge_by_enum', function() {
      return correctly_draw(by_enum.draw_by_merge);
    });
  });

}).call(this);

//# sourceMappingURL=drawing_skyline_spec.map
