// Generated by CoffeeScript 1.7.1
(function() {
  var Enum;

  Enum = require('../enum');

  describe("External Enumerator", function() {
    var arr;
    arr = [1, 2, 3];
    it("should be able to iterate an array", function() {
      var e, result;
      result = [];
      e = Enum.Enum(arr);
      Enum.loop(function() {
        return result.push(e.next());
      });
      return expect(result).toEqual(arr);
    });
    return it("should be able to peek, without forward", function() {
      var e;
      e = Enum.Enum(arr);
      e.next();
      expect(e.peek()).toEqual(2);
      return expect(e.peek()).toEqual(2);
    });
  });

}).call(this);

//# sourceMappingURL=loop_spec.map
